ServerSide-Project/Controllers/ClassificationController.cs
using ServerSide_Project.Tools;
using Service.Managers;
using Service.Models;
using Service.Validations;
using System.Linq;
using System.Web.Mvc;

namespace ServerSide_Project.Controllers
{
    public class ClassificationController : ControllerExtension
    {
        private ClassificationManager _Manager { get; } = new ClassificationManager();

        [HttpGet]
        public ActionResult ListClassifications(int id)
        {
            return View("ListBooks", _Manager.GetBooksByClassification(id));
        }

        [HttpGet]
        [RestoreModelStateFromTempData]
        public ActionResult EditClassification(int id)
        {
            AuthorizeAndRedirect();
            return View("EditClassification", _Manager.GetClassificationFromID(id));
        }

        [HttpPost]
        [SetTempDataModelState]
        [ValidateAntiForgeryToken]
        public ActionResult EditClassification(Classification classification)
        {
            AuthorizeAndRedirect();
            ClassificationValidation validation = _Manager.EditClassification(classification);
            if (!validation.IsValid)
            {
                ValidationMessages.ConvertCodeToMsg(ModelState, validation.ErrorDict);
                return RedirectToAction("EditClassification", new { classification.SignId });
            }
            ModelState.Clear();
            return RedirectToAction("BrowseAllBooks", "Book", null);
        }

        [HttpGet]
        [RestoreModelStateFromTempData]
        public ActionResult CreateClassification()
        {
            AuthorizeAndRedirect();
            return View("CreateClassification");
        }

        [HttpPost]
        [SetTempDataModelState]
        [ValidateAntiForgeryToken]
        public ActionResult CreateClassification(Classification classification)
        {
            AuthorizeAndRedirect();
            ClassificationValidation validation = _Manager.CreateClassification(classification);
            if (!validation.IsValid)
            {
                ValidationMessages.ConvertCodeToMsg(ModelState, validation.ErrorDict);
                return RedirectToAction("CreateClassification");
            }
            ModelState.Clear();
            return RedirectToAction("BrowseAllBooks", "Book", null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteClassificationPost(int id)
        {
            AuthorizeAndRedirect();
            ClassificationValidation validation = _Manager.DeleteClassification(_Manager.GetClassificationFromID(id));
            if (validation.IsValid)
                return RedirectToAction("BrowseAllBooks", "Book", null);
            ValidationMessages.ConvertCodeToMsg(ModelState, validation.ErrorDict);
            return View("DeleteClassification", _Manager.GetClassificationFromID(id));
        }

        [HttpGet]
        public ActionResult DeleteClassification(int id)
        {
            AuthorizeAndRedirect();
            return View("DeleteClassification", _Manager.GetClassificationFromID(id));
        }

        [HttpGet]
        public ActionResult GetClassifications(int[] classifications = null)
        {
            return PartialView("ListClassifications", new ListClassification()
            {
                Classifications = _Manager.GetAllClassifications(),
                SelectedClassification = classifications?.ToList()
            });
        }

        [HttpGet]
        public ActionResult GetClassificationDropdown()
        {
            return PartialView("ClassificationDropdown", _Manager.GetAllClassifications());
        }
    }
}

ServerSide-Project/Views/Shared/Classification.cshtml
@model List<Service.Models.Classification>

<div class="panel panel-default" id="classificationPanel">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="trigger collapsed">
                Classifications
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            @foreach (var classification in Model)
            {
                <div class="row">
                    <div class="col-sm-12 text-left">
                            <input name=classifications type="checkbox" value=@classification.SignId.ToString() id=@classification.Signum>
                            <label for=@classification.Signum>@classification.Signum</label>
                    </div>
                    <div class="col-sm-10 text-right">
                        @Html.ActionLink("Edit", "EditClassification", "Classification", new { id = classification.SignId }, null) |
                        @using (Html.BeginForm("DeleteClassification", "Classification", new { id = classification.SignId }, FormMethod.Post, new { @class = "form-group", @id = "classificationListOptions"}))
                        {
                            @Html.AntiForgeryToken()
                            <input type="submit" value="Delete" class="btn-link" />
                        }
                    </div>
                </div>
            }
        </div>
    </div>
</div>

ServerSide-Project/Views/Shared/ListAuthors.cshtml
@using PagedList.Mvc
@using Service.Models
@model PagedList.IPagedList<Service.Models.Author>

@{
    ViewBag.Title = "ListAuthors";
    ViewBag.activeBrowseBy = "Author";
}

<div class="row">
    <div class="col-sm-12 text-center">
        <h2>Authors</h2>
    </div>
    @if (Session["Level"] != null && (Rank)Session["Level"] >= Rank.Editor)
    {
        <div class="col-sm-offset-3 col-sm-9 text-left">
            @Html.ActionLink("Create New Author", "CreateAuthor", "Author", null, null)
        </div>
    }
</div>

<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6" id="authorListOuter">
        @foreach (var item in Model)
        {
            <div class="row" id="authorListItem">
                <div class="col-sm-1" id="authorImage">
                    <img src="~/Resources/Author.png" width="80%" height="80%" class="text-center" />
                </div>
                <div class="col-sm-3" id="authorListName">
                    @Html.ActionLink(HttpUtility.HtmlDecode(item.FullName), "ListAuthorDetails", "Author", new { id = item.Aid }, null)
                </div>
                <div class="col-sm-2 text-right">
                    <div class="row">
                        <p class="listHeadline">Year of Birth:</p>
                    </div>
                    <div class="row">
                        @if (item.BirthYear == null)
                        {
                            <span>Unknown</span>
                        }
                        else
                        {
                            @Html.Encode(item.BirthYear);
                        }
                    </div>
                </div>
                <div class="col-sm-2 text-right">
                    @if (Session["Level"] != null && (Rank)Session["Level"] >= Rank.Editor)
                    {
                        @Html.ActionLink("Edit", "EditAuthor", "Author", new { id = item.Aid }, null);
                        @Html.Raw(" | ")
                        @Html.ActionLink("Delete", "DeleteAuthor", "Author", new { id = item.Aid }, null);
                    }
                </div>
            </div>
        }
    </div>
    <div class="col-sm-3"></div>
</div>

ServerSide-Project/Views/Shared/ListBooks.cshtml
@using PagedList.Mvc
@using Service.Models
@model PagedList.IPagedList<Service.Models.Book>

@{
    ViewBag.activeBrowseBy = "Book";
}

@if (Session["Level"] != null && (Rank)Session["Level"] >= Rank.Editor)
{
    <p class="text-left">
        @Html.ActionLink("Create New Book", "CreateBook", "BookAuthorClassification")
    </p>
}

<div class="row" id="bookListOuter">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="row text-left" id="bookListItem">
            <div class="col-sm-2">
                @{
                    string ClassificationPictureString = "~/Resources/";
                    ClassificationPictureString += Model[i].Classification.Signum += ".png";
                    if (@Model[i].Classification.Signum[0] == 'P' && @Model[i].Classification.Signum[1] == 'u' && @Model[i].Classification.Signum[2] == 'b')
                    {
                        ClassificationPictureString = "~/Resources/Education.png";
                    }
                }
                <img src="@Url.Content(ClassificationPictureString)" id="bookListImage" />
            </div>
            <div class="col-sm-9">
                <div class="row">
                    <div class="col-sm-9" id="bookListTitle">
                        @Html.ActionLink(HttpUtility.HtmlDecode(@Model[i].Title), "ListBookDetails", "Book", new { id = @Model[i].ISBN }, null)
                    </div>
                    <div class="col-sm-3 text-right" id="bookListAdminPane">
                        @if (Session["Level"] != null && (Rank)Session["Level"] >= Rank.Editor)
                        {
                            @Html.ActionLink("Edit", "EditBook", "BookAuthorClassification", new { id = @Model[i].ISBN }, new { @class = "" });
                            @Html.Raw(" | ");
                            @Html.ActionLink("Delete", "DeleteBook", "Book", new { id = @Model[i].ISBN }, null);
                        }
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-5" id="bookListAuthor">
                        <p class="listHeadline">Authors:</p>
                    </div>
                    <div class="col-sm-2" id="bookListPublicationYear">
                        <p class="listHeadline">Published:</p>
                    </div>
                    <div class="col-sm-3" id="bookListISBN">
                        <p class="listHeadline">ISBN:</p>
                    </div>
                    <div class="col-sm-2" id="bookListPages">
                        <p class="listHeadline">Pages:</p>
                    </div>
                </div>
                <div class="row" id="bookListInfoRow">
                    <div class="col-sm-5" id="bookListAuthor">
                        @if (Model[i].Authors[0].FirstName != "No Author")
                        {
                            foreach (var author in @Model[i].Authors)
                            {
                                @Html.ActionLink(HttpUtility.HtmlDecode(author.FullName), "ListAuthorDetails", "Author", new { id = author.Aid }, null)
                                if (!@Model[i].Authors.Last().Equals(author))
                                {
                                    <span>
                                        |
                                    </span>
                                }
                            }
                        }
                        else
                        {
                            @Html.Encode("No Author Available");
                        }
                    </div>
                    <div class="col-sm-2" id="bookListPublicationYear">
                        @Model[i].PublicationYear
                    </div>
                    <div class="col-sm-3" id="bookListISBN">
                        @Model[i].ISBN
                    </div>
                    <div class="col-sm-2" id="bookListPages">
                        @Model[i].Pages
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <p class="listHeadline">Description:</p>
                    </div>
                </div>
                <div class="row" id="bookListDescription">
                    <div class="col-sm-12">
                        @Model[i].ShortDescription
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ServerSide-Project/Views/Shared/ListClassifications.cshtml
@model Service.Models.ListClassification
@using Service.Models

<div class="panel panel-default" id="classificationPanel">
    <div class="panel-heading" role="tab" id="headingOne">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="trigger collapsed">
                Classifications
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
        <div class="panel-body">
            @{
                foreach (var classification in Model.Classifications)
                {
                    <div class="row">
                        <div class="col-sm-12 text-left">
                            <input name=classifications type="checkbox" value=@classification.SignId.ToString() id=@classification.Signum @Html.Raw((Model.SelectedClassification!=null && Model.SelectedClassification.Any(x => x.Equals(classification.SignId) )) ? "checked=\"checked\"" : "")/>
                            <label for=@classification.Signum title="@classification.Description" >@classification.Signum</label>
                        </div>
                            @if (Session["Level"] != null && (bool)Session["classificationEditor"])
                            {
                                <div class="col-sm-10 text-right">
                                    @Html.ActionLink("Edit", "EditClassification", "Classification", new { id = classification.SignId }, null) |
                                    @Html.ActionLink("Delete", "DeleteClassification", "Classification", new { id = classification.SignId }, null)
                                </div>
                            }
                    </div>
                }
            }
        </div>
    </div>
</div>

ServerSide-Project/Views/Shared/_Layout.cshtml
@using Service.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Server-side Web Development Project</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/sticky-footer.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/layout.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-slider.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-slider.min.css" rel="stylesheet" />
    <script src="js/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="js/shieldui-all.min.js" type="text/javascript"></script>
</head>
<body>
    <div id="wrap">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <div class="navbar-header col-sm-12 ">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="col-sm-4">
                        <ul class="nav nav-pills nav-justified">
                            <li class="@((ViewBag.activeBrowseBy == "Book") ? "active" : null) " >@Html.ActionLink("Books", "BrowseAllBooks", "Book")</li>
                            <li class="@((ViewBag.activeBrowseBy == "Author") ? "active" : null) " >@Html.ActionLink("Authors", "BrowseAllAuthors", "Author")</li>
                        </ul>
                    </div>
                    <div class="navbar-col-sm-4 col-sm-offset-5">
                        @Html.ActionLink("Jönköping Library", "Index", "Home", null, new { @class = "navbar-brand", @id = "webPageHeadline" })
                    </div>
                    <div class="navbar-col-sm-4">
                        <ul class="nav navbar-nav navbar-right">
                            @if (Session["Level"] != null && (Rank)Session["Level"] >= Rank.Editor)
                            {
                                <li id="headerNamedisplay">
                                    <p>
                                        @Html.DisplayName((Session["Authentication"]).ToString() + ": ")
                                        @Html.DisplayName(((Rank)Session["Level"]).ToString())
                                    </p>
                                </li>
                                <li>@Html.ActionLink("Admin Panel", "AdminPanel", "Admin", null, null)</li>
                                <li>
                                    @using (@Html.BeginForm("Logout", "Admin", FormMethod.Post, new { @class = "form-group", @id = "logOutButton" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <button type="submit" class="btn btn-link"><span class="glyphicon glyphicon-log-out"></span> Sign Out</button>
                                    }
                                </li>
                            }
                            else
                            {
                                <li><a href=@Url.Action("Login", "Admin") id="logInButton"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container-fluid text-center">
            <div class="content">
                <div class="row text-center">
                    @if (ViewBag.activeBrowseBy == "Book")
                    {
                        string search = Request.Params["search"];
                        using (Html.BeginForm("SearchBooks", "Book", FormMethod.Get, new { @class = "form-inline" }))
                        {
                            Html.AntiForgeryToken();
                            <div class="form-group col-sm-12 input-lg text-center" id="searchBar">
                                <input type="text" name="search" class="form-control" id="searchField" value="@search" placeholder="Search for books">
                                <button class="btn btn-default" type="submit" id="searchBtn">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>

                            <div class="col-sm-2 sidenav float-left align-top text-center container" id="classificationOuter">
                                @if (Session["Level"] != null && (bool)Session["classificationEditor"])
                                {
                                    <div class="row">
                                        @Html.ActionLink("Create New Classification", "CreateClassification", "Classification", null, null)
                                    </div>
                                }
                                <div class="collapse-group">
                                    @{Html.RenderAction("GetClassifications", "Classification");}
                                </div>
                            </div>

                            <div class="col-sm-8">
                                @RenderBody()
                            </div>
                            }
                            }
                            else if (ViewBag.activeBrowseBy == "Author")
                            {
                                string search = Request.Params["search"];
                                using (Html.BeginForm("SearchAuthors", "Author", FormMethod.Get, new { @class = "form-inline" }))
                                {
                                    Html.AntiForgeryToken();
                                    <div class="form-group col-sm-12 input-lg text-center" id="searchBar">
                                        <input type="text" name="search" class="form-control" value="@search" id="searchField" placeholder="Search for authors">
                                        <button class="btn btn-default" type="submit" id="searchBtn">
                                            <i class="glyphicon glyphicon-search"></i>
                                        </button>
                                    </div>
                                }
                                @RenderBody()
                            }
                            else
                            {
                                @RenderBody()
                            }
                </div>
            </div>
        </div>
    </div>

    <footer id="footer">
        <div class="navbar align-center footerText">
            <div class="text-muted col-sm-12 text-center">©@DateTime.Today.Year@Html.Raw("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Created by: Filip Andersson & Jonatan Flyckt")@Html.Raw("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Contact: fljo1589@student.ju.se, anfi1622@student.ju.se")</div>
        </div>
    </footer>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-slider.js"></script>
    <script src="~/Scripts/bootstrap-slider.min.js"></script>
</body>
</html>